export {default as Hero} from "./HeroSlider"
export {default as HeroS} from "./HeroSoild"
export {default as Contact} from "./ContactSection"
export {default as Services} from "./ServicesSection"
export {default as Stats} from "./StatsSection"
export {default as WhyUs} from "./WhyUsSection"
export {default as Testimonial} from "./TestimonialSection"
export {default as CTA} from "./CTASection"